services:
  auth:
    build: "Auth/"
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
  users:
    build: "Users/"
    environment:
      - PORT=4001
    ports:
      - "4001:4001"
  notes:
    build: "Notes/"
    environment:
      - PORT=4002
    ports:
      - "4002:4002"
  